{
 "title": "isp",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "fast.com",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "expr": "fast_com_default", "legendFormat": "Overall Mbit/s" },
    { "expr": "fast_com_ipv4", "legendFormat": "IP v4 Mbit/s" },
    { "expr": "fast_com_ipv6", "legendFormat": "IP v6 Mbit/s" }
   ]
  },
  {
   "title": "speedtest",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "expr": "speedtest_download", "legendFormat": "Down Mbit/s" },
    { "expr": "speedtest_upload", "legendFormat": "UP Mbit/s" }
   ]
  },
  {
   "title": "Ping ms",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "speedtest_ping", "legendFormat": "ms" }
   ]
  }
 ]
}